server:
  port: 8086

spring:
  application:
    name: es-application
  elasticsearch:
    uris: http://localhost:9200
#    username: admin
#    password: admin

# rabbitmq配置
rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest

