server:
  port: 8084

spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
  application:
    name: coupon-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_coupon?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 114706
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.coupon.pojo

# redis配置
redis:
  host: localhost
  port: 6379
# rabbitmq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#Seata配置
seata:
  tx-service-group: my_test_tx_group # 一定用这个默认的
  enabled: true
  registry: # 注册中心
    # 配置 seata 的注册中心, 告诉 seata client 怎么去访问 seata server 事务协调者进行通信
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # seata-server 所在的注册中心地址
      application: seata-server # 指定 seata-server 在注册中心的 服务名， (默认 seata-server)
      username: nacos
      password: nacos
      group: SEATA_GROUP # 默认 SEATA_GROUP
      namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
  config:
    # 配置 seata 的配置中心，可以读取关于 seata client 的一些配置，即 "seata\seata\script\config-center\config.txt" 中的配置
    type: nacos
    nacos: # 配置中心
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
