server:
  port: 9201

spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务注册中心地址
        namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4 # 命名空间ID
    sentinel:
      transport:
        dashboard: localhost:8080  # Sentinel控制台地址
        port: 8719                 # Sentinel客户端监听端口（用于与Dashboard通信）
        heartbeat-interval-ms: 30000  # 心跳间隔（保持与控制台连接）
      filter:
        enabled: false             # 关闭默认过滤器（使用自定义流控规则）
      gateway:
        enabled: true              # 开启网关流控功能
        api-response:
          http-status: 429        # 流控返回的HTTP状态码
          content-type: application/json
          body: '{"code":429,"msg":"系统繁忙，请稍后重试"}'  # 自定义流控响应
      scg:
        fallback:
          mode: response           # 流控模式（直接返回响应）
          response-body: '{"code":403,"msg":"非法请求，拒绝访问"}'  # 非法请求响应
        url-patterns:
          - /**                    # 保护所有接口
          - "'!/api/auth/*,/api/captcha/*,/api/files/*,/api/payment/*'"    # 排除认证接口（与白名单配合）
    gateway:
      discovery:
        locator:
          enabled: true            # 启用服务发现路由
      globalcors:                  # 跨域配置
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://localhost:8083"
              - "http://localhost:8084"
              - "http://localhost:8085"
              - "http://localhost:8087"
              - "http://localhost:8088"
            allowedMethods: ["GET","POST","DELETE","PUT","OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

# 网关路由配置（从Nacos动态读取）
gateway:
  routes:
    config:
      data-id: gateway-route
      group: DEFAULT_GROUP
      namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4

# 白名单路径（直接放行）
url:
  white:
    list: /api/auth,/api/captcha,/api/payment/

# Seata分布式事务配置
seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
