server:
  port: 8082

spring:
  cloud:
    nacos:
      server-addr: localhost:8848/nacos/index.html
      discovery:
        namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 114706
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

# rabbitmq配置
rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest
  # 消息队列监听器配置
  listener:
    simple:
      acknowledge-mode: manual  # 消息开启手动确认
  # 延时队列
  exchanges:
    order.delay.exchange:
      name: order.delay.exchange
      type: x-delayed-message
      durable: true
      arguments:
        x-delayed-type: direct
  # 延时队列绑定
  queues:
    order.delay.queue:
      name: order.delay.queue
      durable: true
  # 延时队列绑定
  bindings:
    order.delay.binding:
      exchange: order.delay.exchange
      queue: order.delay.queue
      routing-key: order.delay.routing.key

