server:
  port: 8083

spring:
  application:
    name: product-service
  main:
    lazy-initialization: true  # 确保延迟初始化开启
  elasticsearch:
    uris: http://localhost:9200
  #    username: admin
  #    password: admin
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9ae782ba-77b6-43cd-b1be-0dcf25721ff4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_product?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 114706
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.product.pojo  # 指定别名包路径

# rabbitmq配置
rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest


# 静态资源映射
web:
  resources:
    static-locations: classpath:/files/

#上传文件的保存路径
reggie:
  path: D:/exploitation/work1/LocalLife/product-service/src/main/resources/files
